### ISSUE TITLE
"Match.html" Game logic BUG

### ISSUE THREAD

**Issue by YeeOreo** [YiKaiWu1125/word_card#20]
根據先前的：
1. Commit： 8ad856b970778cd35ddcb000a33d38b909cd5081

2. Pull Request： #11 
---
- BUG：拖動元素時，位置偏移

**Comment by YiKaiWu1125** [comment]
能在1/3前修復完畢嗎

**Comment by YeeOreo** [comment]
已經修復完畢，尚未push而已
